### ISSUE TITLE
Do not mistake three slashes for comment lines

### ISSUE THREAD

**Issue by jhradilek** [msuchane/presciidoc#1]
The current version of `presciidoc` currently interprets three forward slashes at a beginning of a line as a comment line and when ran with the `-c` option, removes such lines from the output:

```
$ cat test.adoc 
/// This is not a comment
$ presciidoc -c test.adoc 
$
```

AsciiDoctor however defines line comments as exactly two forward slashes at the beginning of the line followed either by the end of line or any character other than another forward slash. As a consequence, the `asciidoctor` utility interprets lines starting with three forward slashes as regular paragraphs:

```
$ asciidoctor -so - test.adoc 
<div class="paragraph">
<p>/// This is not a comment</p>
</div>
```

I believe `presciidoc` should match this behavior.

**Comment by msuchane** [comment]
This is now resolved in presciidoc version 0.3.0.

Thanks for the bug report!
