### ISSUE TITLE
Recognize more than four slashes as comment blocks

### ISSUE THREAD

**Issue by jhradilek** [msuchane/presciidoc#2]
The current version of `presciidoc` only recognizes comment blocks that use exactly four forward slashes as their delimiter. Consider the following file:

```
$ cat test.adoc 
This line should be displayed.

/////
This line is a block comment. The following line does not terminate this block either:
////
This line is a continuation of the block comment.
/////

This line should also be displayed.
```

AsciiDoctor allows four or more forward slashes as comment block delimiters and requires the same amount of slashes to close the open comment block. Because of that, it only displays the first and the last line of the example above:

```
$ asciidoctor -so - test.adoc 
<div class="paragraph">
<p>This line should be displayed.</p>
</div>
<div class="paragraph">
<p>This line should also be displayed.</p>
</div>
```

Because of the current behavior, `presciidoc` fails to recognize the initial opening of the comment block and displays it as regular lines. It then mistreats the four slashes that are inside a comment block and should be ignored as an opening of a comment block that is then never closed:

```
$ presciidoc -c test.adoc 
This line should be displayed.


This line is a block comment. The following line does not terminate this block either:





```

I believe `presciidoc` should match the behavior of `asciidoctor`.

**Comment by msuchane** [comment]
This is now resolved in presciidoc version 0.3.0.

Thanks for the bug report!
