### ISSUE TITLE
Do not remove the new line character from the last line

### ISSUE THREAD

**Issue by jhradilek** [msuchane/presciidoc#3]
The current version of `presciidoc` artificially removes the newline character from the very last line. I realize some editors prefer to store files without this character on the last line, but as `presciidoc` is intended to be used on the front of the command line pipe, this can contribute to unexpected and incorrect output.

Consider the following file (notice that the command prompts start on a new line):

```
$ cat test.adoc 
First line.
Second line.
$ wc -l test.adoc
2 test.adoc
```

When processed by `presciidoc`, the last newline character disappears which confuses some standard utilities:

```
$ presciidoc test.adoc 
First line.
Second line.$ presciidoc test.adoc | wc -l
1
```

I know Bash has many known pitfalls, but the most unexpected one is that when the last line does not have a newline character, the `while read` loop completely ignores it:

```
$ presciidoc test.adoc | while read line; do echo "Line: '$line'"; done
Line: 'First line.'
```

There is a workaround for it but as `presciidoc` is intended to be used for these types of tasks, I would recommend that it does not artificially strip the last newline if it is present in the file, even maybe adds it when it is not so that it guarantees predictable output.

**Comment by msuchane** [comment]
This is now resolved in presciidoc version 0.3.0.

Thanks for the bug report!
